import Link from "next/link";
import { ContentCard } from "@/components/content-card";
import { SectionHeading } from "@/components/section-heading";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { communityCards, contentCards, localCards } from "@/lib/mock-content";

const trends = ["Beauty", "Fashion", "Food", "Lifestyle"];

export default function Home() {
  return <main className="min-h-screen overflow-hidden bg-[#fcfcfa] text-[#18201d]"><SiteHeader />
    <section className="relative mx-auto max-w-7xl px-5 pb-16 pt-7 sm:px-8 sm:pb-24 lg:px-10 lg:pb-28 lg:pt-12"><div className="absolute right-[-15%] top-12 -z-0 size-72 rounded-full bg-[#e7f0d8] blur-3xl sm:right-[10%]" /><div className="relative grid items-center gap-12 lg:grid-cols-[1fr_0.9fr] lg:gap-16"><div className="max-w-2xl"><p className="mb-5 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-[#71816d]"><span className="size-2 rounded-full bg-[#b2cf76]" />Your Korea, your way</p><h1 className="text-5xl font-semibold tracking-[-0.065em] text-[#17201d] sm:text-6xl lg:text-7xl">Discover Korea <span className="text-[#789a50]">Beyond</span> the Screen</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#626c66]">Discover Korean culture, explore local Korea, and connect with people who love Korea.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="inline-flex items-center justify-center gap-2 rounded-full bg-[#17201d] px-6 py-3.5 text-sm font-semibold text-white transition hover:-translate-y-0.5 hover:bg-[#35413c]" href="/local-korea">Explore Korea <span>→</span></Link><Link className="inline-flex items-center justify-center rounded-full border border-[#ccd2cb] bg-white px-6 py-3.5 text-sm font-semibold text-[#26302b]" href="/signup">Join the Community</Link></div><div className="mt-10 flex items-center gap-4 text-sm text-[#69736c]"><div className="flex -space-x-2"><span className="size-8 rounded-full border-2 border-white bg-[#f5b9a4]" /><span className="size-8 rounded-full border-2 border-white bg-[#7da7b2]" /><span className="size-8 rounded-full border-2 border-white bg-[#d5a6c5]" /></div><span>Join travelers and culture lovers worldwide</span></div></div>
      <div className="relative mx-auto w-full max-w-md lg:max-w-none"><div className="aspect-[4/4.5] overflow-hidden rounded-[2rem] bg-[#cfe1d1] p-5 shadow-2xl shadow-[#93ad8f]/25"><div aria-label="Abstract placeholder for a local Seoul guide" className="relative flex h-full flex-col justify-between overflow-hidden rounded-[1.4rem] border border-white/40 bg-[linear-gradient(145deg,#669286_0%,#a7c5aa_42%,#ece0bd_100%)] p-5"><div className="absolute -right-10 top-20 size-40 rounded-full border-[18px] border-white/15" /><div className="relative flex justify-between"><span className="rounded-full bg-white/85 px-3 py-1.5 text-xs font-semibold">Seoul, Korea</span><span className="grid size-8 place-items-center rounded-full bg-[#17201d] text-white">⌖</span></div><div className="relative"><p className="mb-2 text-[10px] font-semibold uppercase tracking-[0.16em] text-white/75">Local image preview</p><div className="rounded-2xl bg-white/88 p-4 backdrop-blur"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#728071]">Featured local guide</p><p className="mt-1 text-xl font-semibold tracking-tight">A quieter side of Seongsu</p><div className="mt-3 flex items-center justify-between text-xs text-[#647068]"><span>By Mina, Seoul</span><span>⌖ 12 spots</span></div></div></div></div></div><div className="absolute -bottom-5 -left-3 rounded-2xl border border-white/60 bg-white/90 p-3.5 shadow-lg backdrop-blur sm:-left-7"><p className="text-xs text-[#718078]">Community favorites</p><p className="mt-0.5 text-sm font-semibold">4.9 <span className="text-[#e49a37]">★★★★★</span></p></div></div></div></section>
    <ContentSection eyebrow="Culture, curated" title="K-Contents" copy="Follow the stories, sounds, and creative moments shaping Korea now." cards={contentCards} bordered />
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24 lg:px-10"><div className="rounded-[2rem] bg-[#1c2924] px-5 py-10 text-white sm:px-10 sm:py-14"><SectionHeading dark eyebrow="Plan less. Feel more." title="Discover Local Korea" copy="Go beyond the guidebook with places and people that make every visit feel personal." /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{localCards.map((card) => <ContentCard card={card} key={card.title} />)}</div></div></section>
    <section className="border-y border-[#e4e8e1] bg-[#f4f7f0] py-16 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10"><SectionHeading eyebrow="Now in Korea" title="K-Trends" copy="The things people are talking about, wearing, tasting, and taking home." /><div className="mt-9 grid grid-cols-2 gap-3 md:grid-cols-4">{trends.map((trend, index) => <Link className="group relative flex aspect-square flex-col justify-between overflow-hidden rounded-2xl bg-[#d7e5d4] p-4" href="/k-trends" key={trend}><div className={`absolute inset-0 opacity-90 ${["bg-[radial-gradient(circle_at_25%_20%,#fff5cb,transparent_30%),linear-gradient(140deg,#bdcfa2,#789c7c)]", "bg-[radial-gradient(circle_at_70%_20%,#ffe5cb,transparent_30%),linear-gradient(140deg,#d3a5a5,#817b98)]", "bg-[radial-gradient(circle_at_30%_70%,#f6e3b1,transparent_30%),linear-gradient(140deg,#d39857,#a76f50)]", "bg-[radial-gradient(circle_at_70%_70%,#ead7ff,transparent_30%),linear-gradient(140deg,#afbbd7,#7e9a86)]"][index]}`} /><span className="relative text-xs font-semibold uppercase tracking-[0.14em] text-white/80">Trending now</span><div className="relative flex items-end justify-between"><h3 className="text-2xl font-semibold tracking-tight text-white">{trend}</h3><span className="text-white">↗</span></div></Link>)}</div></div></section>
    <ContentSection eyebrow="Community preview" title="Connect with people who love Korea" copy="Ask, share, and find your people—whether Korea is home, a dream, or your next destination." cards={communityCards} />
    <section className="mx-auto max-w-7xl px-5 pb-16 sm:px-8 sm:pb-24 lg:px-10"><div className="relative overflow-hidden rounded-[2rem] bg-[#efc5b4] px-6 py-10 sm:px-10 sm:py-14"><div className="absolute -right-12 -top-20 size-72 rounded-full bg-[#cf735a]/25 blur-2xl" /><div className="relative grid gap-8 lg:grid-cols-[1fr_0.8fr] lg:items-center"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#8d4c3b]">What&apos;s happening</p><h2 className="mt-4 max-w-xl text-4xl font-semibold tracking-[-0.055em] text-[#432f2b] sm:text-5xl">Meet Korea in the moment.</h2><p className="mt-4 max-w-lg text-base leading-7 text-[#75564e]">Discover cultural gatherings, pop-ups, workshops, and community events happening across Korea.</p><Link className="mt-7 inline-flex rounded-full bg-[#432f2b] px-5 py-3 text-sm font-semibold text-white" href="/events">Browse events →</Link></div><div className="rounded-2xl border border-white/50 bg-white/65 p-5 text-sm text-[#59423c]"><p className="text-xs text-[#876a60]">This weekend in Seoul</p><p className="mt-1 font-semibold">A community guide to September</p><div className="mt-5 space-y-3 border-t border-[#dfb6a7] pt-4"><p>Han River sunset picnic <span className="float-right text-[#9a6e5d]">Fri · 6 PM</span></p><p>Indie film night <span className="float-right text-[#9a6e5d]">Sat · 7 PM</span></p><p>Local maker&apos;s market <span className="float-right text-[#9a6e5d]">Sun · 11 AM</span></p></div></div></div></div></section><SiteFooter /></main>;
}

function ContentSection({ eyebrow, title, copy, cards, bordered = false }: { eyebrow: string; title: string; copy: string; cards: typeof contentCards; bordered?: boolean }) {
  return <section className={bordered ? "border-y border-[#e4e8e1] bg-white/70 py-16 sm:py-20" : "mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24 lg:px-10"}><div className={bordered ? "mx-auto max-w-7xl px-5 sm:px-8 lg:px-10" : ""}><SectionHeading eyebrow={eyebrow} title={title} copy={copy} /><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{cards.map((card) => <ContentCard card={card} key={card.title} />)}</div></div></section>;
}
