"use client";
import { useRef,useState } from "react";
import { useRouter } from "next/navigation";
import { saveCluster,saveClusterLink,saveClusterPrompt,removeClusterEntry } from "@/app/admin/clusters/actions";
import { targets,promptKinds,type Cluster,type Prompt,type Target } from "@/lib/clusters";
const input="mt-2 block w-full min-w-0 rounded-xl border border-[#ccd2cb] bg-white p-3";
const button="rounded-full bg-[#17201d] px-5 py-3 text-white disabled:opacity-50";
type Result={ok:boolean;message:string;id?:string;revision?:string};
function useSave(){const router=useRouter();const lock=useRef(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");return {busy,message,run:async(action:()=>Promise<Result>,onSuccess?:(r:Result)=>void)=>{if(lock.current)return;lock.current=true;setBusy(true);try{const r=await action();setMessage(r.message);if(r.ok){onSuccess?.(r);router.refresh();}}catch{setMessage("Could not confirm the save. Check the list before retrying.");}finally{lock.current=false;setBusy(false);}}};}
export function ClusterEditor({cluster}:{cluster?:Cluster}){const {busy,message,run}=useSave();const router=useRouter();const [revision,setRevision]=useState(cluster?.updated_at);
  return <form className="space-y-5 rounded-2xl border bg-white p-6" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>saveCluster(cluster?.id??null,revision,f),r=>{setRevision(r.revision);if(!cluster&&r.id)router.replace(`/admin/clusters/${r.id}`);});}}><fieldset disabled={busy} className="space-y-5">{([['slug',80],['title',160],['summary',500],['introduction',10000]] as const).map(([key,max])=><label className="block capitalize" key={key}>{key}{key==='introduction'||key==='summary'?<textarea name={key} defaultValue={cluster?.[key]} required maxLength={max} rows={key==='introduction'?7:3} className={input}/>:<input name={key} defaultValue={cluster?.[key]} required maxLength={max} className={input}/>}</label>)}<label className="block">Display order<input type="number" name="display_order" required min={0} max={9999} defaultValue={cluster?.display_order??0} className={input}/></label><label className="block">Publication<select name="status" defaultValue={cluster?.status??"draft"} className={input}><option value="draft">Draft</option><option value="published">Published</option></select></label><p className="text-sm">Publishing this topic does not publish connected drafts. Homepage shows the first four published topics by display order. Changing a slug changes its public URL.</p><button className={button}>{busy?"Saving…":"Save topic"}</button></fieldset><p role="status">{message}</p></form>;
}
export type Candidate={id:string;title:string;target:Target;status:string};
export type AdminLink={id:string;display_order:number;label:string};
export function ClusterConnections({clusterId,links,candidates}:{clusterId:string;links:AdminLink[];candidates:Candidate[]}){const {busy,message,run}=useSave();return <section className="mt-10"><h2 className="text-2xl font-semibold">Connected content</h2><p className="my-4 text-sm">Lower order appears first within each content type. Draft targets stay private. Duplicate connections are blocked.</p><form className="space-y-4 rounded-2xl border bg-white p-6" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const [target,id]=String(f.get('choice')).split(':');f.set('target',target);f.set('target_id',id??'');void run(()=>saveClusterLink(clusterId,null,f));}}><label className="block">Existing content<select name="choice" required disabled={busy} className={input}><option value="">Choose an existing item</option>{candidates.map(c=><option key={`${c.target}:${c.id}`} value={`${c.target}:${c.id}`}>{targets[c.target].label} — {c.title} ({c.status})</option>)}</select></label><label className="block">Order<input name="display_order" type="number" min={0} max={9999} required defaultValue={0} disabled={busy} className={input}/></label><button disabled={busy} className={button}>Connect content</button></form><div className="mt-5 space-y-3">{links.map(link=><form key={link.id} className="flex flex-wrap items-end gap-3 rounded-xl border bg-white p-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>saveClusterLink(clusterId,link.id,f));}}><p className="w-full break-words">{link.label}</p><label>Order<input name="display_order" type="number" min={0} max={9999} required defaultValue={link.display_order} disabled={busy} className={input}/></label><button disabled={busy} className={button}>Save order</button><button type="button" disabled={busy} className="px-3 py-3 underline" onClick={()=>void run(()=>removeClusterEntry(clusterId,link.id,"item"))}>Disconnect</button></form>)}</div><p role="status" className="mt-3">{message}</p></section>;}
export function ClusterPromptEditor({clusterId,prompt}:{clusterId:string;prompt?:Prompt}){const {busy,message,run}=useSave();const ref=useRef<HTMLFormElement>(null);return <form ref={ref} className="mt-5 space-y-4 rounded-2xl border bg-white p-6" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>saveClusterPrompt(clusterId,prompt?.id??null,f),()=>{if(!prompt)ref.current?.reset();});}}><fieldset disabled={busy} className="space-y-4"><label className="block">Contribution type<select name="kind" defaultValue={prompt?.kind??"question"} className={input}>{promptKinds.map(k=><option key={k}>{k}</option>)}</select></label><label className="block">Editorial participation idea<textarea name="prompt" defaultValue={prompt?.prompt} required minLength={5} maxLength={500} rows={3} className={input}/></label><label className="block">Order<input name="display_order" type="number" min={0} max={9999} required defaultValue={prompt?.display_order??0} className={input}/></label><button className={button}>{prompt?"Save prompt":"Add prompt"}</button>{prompt&&<button type="button" className="ml-3 py-3 underline" onClick={()=>void run(()=>removeClusterEntry(clusterId,prompt.id,"prompt"))}>Remove prompt</button>}</fieldset><p role="status">{message}</p></form>;}
