import Link from "next/link";
import { ContentCard, type ContentCardData } from "@/components/content-card";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

type ListingPageProps = { eyebrow: string; title: string; description: string; filters: string[]; cards: ContentCardData[]; action?: { label: string; href: string } };

export function MvpListingPage({ eyebrow, title, description, filters, cards, action }: ListingPageProps) {
  return <main className="min-h-screen bg-[#fcfcfa] text-[#18201d]"><SiteHeader /><section className="border-y border-[#e4e8e1] bg-[#f4f7f0]"><div className="mx-auto max-w-7xl px-5 py-14 sm:px-8 sm:py-20 lg:px-10"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#789a50]">{eyebrow}</p><div className="mt-4 flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div className="max-w-2xl"><h1 className="text-4xl font-semibold tracking-[-0.06em] sm:text-5xl">{title}</h1><p className="mt-4 text-base leading-7 text-[#69736c]">{description}</p></div>{action && <Link className="w-fit rounded-full bg-[#17201d] px-5 py-3 text-sm font-semibold text-white" href={action.href}>{action.label} →</Link>}</div></div></section><section className="mx-auto max-w-7xl px-5 py-12 sm:px-8 sm:py-16 lg:px-10"><div aria-label="Filters" className="flex flex-wrap gap-2 border-b border-[#e4e8e1] pb-7">{filters.map((filter, index) => <button className={`rounded-full px-4 py-2 text-sm font-medium ${index === 0 ? "bg-[#17201d] text-white" : "border border-[#dce2dc] bg-white text-[#56625a]"}`} type="button" key={filter}>{filter}</button>)}</div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{cards.map((card) => <ContentCard card={card} key={card.title} />)}</div></section><SiteFooter /></main>;
}

export function MvpAccountPage({ kind }: { kind: "login" | "signup" }) {
  const isLogin = kind === "login";
  return <main className="min-h-screen bg-[#fcfcfa] text-[#18201d]"><SiteHeader /><section className="mx-auto grid max-w-7xl gap-8 px-5 py-14 sm:px-8 sm:py-20 lg:grid-cols-[1fr_0.85fr] lg:px-10"><div className="rounded-[2rem] bg-[#1c2924] p-7 text-white sm:p-10"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#b7d093]">Korean Wave Community</p><h1 className="mt-4 text-4xl font-semibold tracking-[-0.06em] sm:text-5xl">{isLogin ? "Welcome back to your Korea." : "Make Korea feel closer."}</h1><p className="mt-5 max-w-md leading-7 text-[#c7d1ca]">{isLogin ? "Pick up the places, stories, and conversations you saved." : "Save discoveries, share experiences, and meet people who love Korea too."}</p><div className="mt-10 grid gap-3 sm:grid-cols-3">{["Save local finds", "Join conversations", "Plan your next visit"].map((item, index) => <div className="rounded-2xl bg-white/10 p-4 text-sm" key={item}><span className="text-[#b7d093]">0{index + 1}</span><p className="mt-5 font-medium">{item}</p></div>)}</div></div><div className="self-center rounded-[2rem] border border-[#e3e7e2] bg-white p-7 sm:p-10"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#789a50]">Account preview</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.05em]">{isLogin ? "Log in" : "Join free"}</h2><p className="mt-3 text-sm leading-6 text-[#717a74]">Account access will be connected in a future MVP step. No account is created on this screen.</p><div className="mt-8 space-y-3"><div className="rounded-xl border border-[#e0e5e0] px-4 py-3 text-sm text-[#929a94]">Email address</div><div className="rounded-xl border border-[#e0e5e0] px-4 py-3 text-sm text-[#929a94]">Password</div><button className="w-full rounded-xl bg-[#dbe4d7] px-4 py-3 text-sm font-semibold text-[#60715c]" type="button" disabled>{isLogin ? "Log in" : "Create account"}</button></div><p className="mt-5 text-center text-xs text-[#8b948d]">Mock UI only · Authentication is not enabled yet</p></div></section><SiteFooter /></main>;
}
